export const GET_PRODUCTS_DATA = 'GET_PRODUCTS_DATA';

// CART
export const ADD_CART = 'ADD_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const ALL_REMOVE_CART = 'ALL_REMOVE_CART';

// FAVORITES

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

// FILTERS
export const ADD_FILTER = 'ADD_FILTER';
